services:
  - type: web
    name: youtube-api
    env: node
    runtime:
      version: 14
    build:
      context:.
      docker:
        dockerfile: Dockerfile
    envVars:
      - key: YOUTUBE_API_KEY
        value: YOUR_YOUTUBE_API_KEY
    region: orego
